### ISSUE TITLE
Docblock tags are interpreted as Projects

### ISSUE THREAD

**Issue by vancoder** [crowdfavorite/wp-capsule#29]
Docblock tags are interpreted as Projects by Capsule.

Example:

/**
- My function.
- 
- @global object $wpdb
- @param string $attachment_url
- @return integer 
  */

This results in the listing of global, param and return as projects.

**Comment by al-esc** [comment]
addressed in capsule-ui, [this commit](https://github.com/crowdfavorite/wp-capsule-ui/commit/97aa9206f4828345b3cf09f95ebf94cbf859b9aa).
projects, code or tags are no longer pulled from code blocks (ie: `` ``` ``` ``) or doc blocks (ie: `/* */`)
