### ISSUE TITLE
Logged out when editing post

### ISSUE THREAD

**Issue by lantrix** [crowdfavorite/wp-capsule#41]
### Using v1.1.1

Whenever I edit a post it logs me out. Tried this cross browser (Chrome/Safari) and cross OS (Mac/Windows).

Logged in prior to edit: http://bit.ly/1lako9K
As soon as clicked on edit: http://bit.ly/1p1AQxe

**Comment by kim07** [comment]
:+1:

**Comment by al-esc** [comment]
Closing as it's outdated
