### ISSUE TITLE
Identify all submodules 

### ISSUE THREAD

**Issue by pur4u** [crowdfavorite/wp-capsule#43]
Identify all the submodules and the functionality used from submodules.
Check:

if the submodules are at the latest version - OK
if there is a develop branch with updated code (CF submodule) - if code is old try to update the master from develop and update to current coding standards
if the submodules are unmaintained forks of external repos - update the project to use the external repo
In the end the submodules will be removed, code from submodules will be included in main project repo or will be included via Composer.

---

External submodules:

- https://github.com/crowdfavorite/jquery.hotkeys
- https://github.com/crowdfavorite/linkify
- https://github.com/crowdfavorite/sidr
- https://github.com/crowdfavorite/jquery-scrollintoview
- https://github.com/crowdfavorite/JSON-js
- https://github.com/crowdfavorite/twitter-text-js
- https://github.com/crowdfavorite/php-markdown-extra-extended
- https://github.com/crowdfavorite/phpjs
- git://github.com/ajaxorg/ace.git
These can be removed and the latest code from corresponding external submodules should be added to the main repo.

CF submodules
- https://github.com/crowdfavorite/wp-taxonomy-filter - old, only master branch, code can be added  to main repo
- https://github.com/crowdfavorite/wp-gatekeeper - develop branch is ahead of master. We need to see if this is used by other projects, test Capsule with develop branch of this submodule, merge develop into master and then the next step is to remove the submodule and add the code into current repo

Copied from [this](https://github.com/crowdfavorite/wp-capsule-server/issues/13)

**Comment by al-esc** [comment]
Closing this as it's tracked in #62
