### ISSUE TITLE
Replace wp_remote_* with wp_safe_remote_*

### ISSUE THREAD

**Issue by mbucurcf** [crowdfavorite/wp-capsule#56]
![Screenshot 2020-04-30 at 16 43 36](https://user-images.githubusercontent.com/23171980/80717556-c2580d00-8b01-11ea-967d-7df3581f8445.png)

https://docs.google.com/document/d/1SCOi8hiucFw58aSdO-8vpV1mxObBRrT8UwqkvYt66V4/edit#

**Comment by al-esc** [comment]
added in [v1.3.0](https://github.com/crowdfavorite/wp-capsule/releases/tag/v1.3.0)
